# Use Nginx with the Alpine variant as the base image
FROM nginx:alpine

# Copy your custom index.html to the Nginx web server directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 for web traffic
EXPOSE 80
