version: '3'
services:
  ros:
    build: .  # Assuming you have a Dockerfile for the ROS setup
    ports:
      - "5000:5000"  # Expose the Flask API port
    networks:
      - my-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/publish_message"]
      interval: 30s
      retries: 3
      start_period: 30s   # Give extra time for Flask to initialize
      timeout: 10s
    env_file:
      - ros.env

  frontend:
    build: ./frontend  # Path to the Dockerfile for frontend
    ports:
      - "5001:80"  # Map frontend port 80 to host port 5001
    networks:
      - my-net  # Ensure both frontend and ros are on the same network
    depends_on:
      - ros
    command: nginx -g 'daemon off;'

  novnc:
    image: theasp/novnc:latest
    ports:
      - "8080:8080"
    networks:
      - my-net
    depends_on:
      - ros
    env_file:
      - novnc.env

networks:
  my-net:
    driver: bridge  # Explicitly define the bridge driver
