version: '3'
services:
  ros:
    build: .
    command: bash -c "source /opt/ros/melodic/setup.bash && roslaunch rosbridge_server rosbridge_websocket.launch"
    volumes: 
      - ./workspace:/root/catkin_ws/
    environment:
      - DISPLAY=novnc:0.0
    env_file:
      - ros.env
    networks:
      - x11

  novnc:  
    image: theasp/novnc:latest
    env_file:
      - novnc.env
    ports:
      - "8080:8080"
    networks:
      - x11

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:80"  # Map port 80 inside container to port 5000 on the host
    networks:
      - x11
    depends_on:
      - ros
networks:
  x11:
